clear variables;
close all;
clc;

addpath 'function';

load('pose_dataset');

f=figure('Name','GUI for subjective view selection assessment','NumberTitle','off');
set(f, 'Tag', 'my window', 'Color', [1 1 1]);

btn_01 = uicontrol('Parent', f,...
                   'Style', 'edit',...
                   'Tag', 'btn01',...
                   'String', 'Subject Name',... 
                   'UserData', struct('name',[]),...
                   'Units', 'normalized',...
                   'Position',[.05 .90 0.2 .05],...
                   'Callback', @btn_Name);

btn_02 = uicontrol('Parent', f,...
                   'Style', 'pushbutton',...
                   'Tag', 'btn02',...
                   'String', 'Start',...
                   'UserData', struct('scene_num',1),...
                   'Units', 'normalized',...
                   'Position', [.1 .1 .1 .05],...
                   'Callback', @btn_Start);

btn_03 = uicontrol('Parent', f,...
                   'Style', 'pushbutton',...
                   'Tag', 'btn03',...
                   'String', 'Submit',...
                   'UserData', struct('cp', [1, 1, 1], 'num_v', 1),...
                   'Units', 'normalized',...
                   'Position', [.45 .1 .1 .05],...
                   'Callback', @btn_Submit);
               
btn_04 = uicontrol('Parent', f,...
                   'Style', 'text',...
                   'Tag', 'btn04',...
                   'String','Pose Name',...
                   'Units', 'normalized',...
                   'BackgroundColor','w',...
                   'Position',[.3 .85 0.4 .1]);
               
btn_05 = uicontrol('Parent', f,...
                   'Style', 'pushbutton',...
                   'Tag', 'btn05',...
                   'String', 'Next',...
                   'Units', 'normalized',...
                   'Position', [.8 .1 .1 .05],...
                   'Callback', @btn_Next);
               
btn_06 = uicontrol('Parent', f,...
                   'Style', 'pushbutton',...
                   'Tag', 'btn06',...
                   'String', 'Refresh',...
                   'Units', 'normalized',...
                   'Position', [.275 .1 .1 .05],...
                   'Callback', @btn_Refresh);

btn_07 = uicontrol('Parent', f,...
                   'Style', 'text',...
                   'Tag', 'btn07',...
                   'String','0',...
                   'Units', 'normalized',...
                   'BackgroundColor','w',...
                   'Position',[.8 .85 0.2 .1]);
               
btn_08 = uicontrol('Parent', f,...
                   'Style', 'pushbutton',...
                   'Tag', 'btn08',...
                   'String', 'Previous',...
                   'Units', 'normalized',...
                   'Position', [.625 .1 .1 .05],...
                   'Callback', @btn_Previous);
                   
